### ISSUE TITLE
401 error getting AWS groups

### ISSUE THREAD

**Issue by danielnovello-pf** [awslabs/ssosync#155]
**401 error getting AWS groups**

All of a sudden, the Lamda function does not work. Its able to retrieve the Google groups, but fails when attempting to get the AWS groups.

**To Reproduce**
1. Create Function URL to run on-demand
2. Ran function and watch CloudWatch logs
3. Removed function and CloudWatch log group
4. Re-deployed function (successfully)
5. Ran function and watch CloudWatch logs - Failed with same error

**Expected behaviour**
Once the function retrieves the Google groups, it's suppose to get the AWS groups and perform a **diff**. Then update/modify the AWS groups

**Additional context**

We have added more policies to allow access to AWS SSO and organizations (Users groups)
The version we are using is [v1.1.0](https://github.com/awslabs/ssosync/releases/tag/v1.1.0) Attempts to use anything never fail

CloudWatch Logs:

`...."collects all google groups..."`
`{
    "group": "AWS Roles - Redacted",
    "id": "Redacted",
    "level": "debug",
    "msg": "get user",
    "time": "2023-11-02T18:33:57Z"
}
`
`{
    "level": "info",
    "msg": "get existing aws groups",
    "time": "2023-11-02T18:33:57Z"
}`
`{
    "level": "error",
    "msg": "error getting aws groups",
    "time": "2023-11-02T18:33:57Z"
}
`
`status of http response was 401: errorString
null`

**Comment by ChrisPates** [comment]
Has you aws SSO access token expired?

It’s the most likely reason for a working deployment stopping working.

Chris

On 2 Nov 2023, at 18:57, danielnovello-pf ***@***.***> wrote:

﻿


401 error getting AWS groups

All of a sudden, the Lamda function does not work. Its able to retrieve the Google groups, but fails when attempting to get the AWS groups.

To Reproduce
Steps to reproduce the behavior:

1.	Create Function URL to run on-demand
2.	Ran function and watch CloudWatch logs
3.	Removed function and CloudWatch log group
4.	Re-deployed function (successfully)
5.	Ran function and watch CloudWatch logs - Failed with same error

Expected behaviour
Once the function retrieves the Google groups, it's suppose to get the AWS groups and perform a diff. Then update/modify the AWS groups

Additional context

We have added more policies to allow access to AWS SSO and organizations (Users groups)
The version we are using is v1.1.0 <https://github.com/awslabs/ssosync/releases/tag/v1.1.0> Attempts to use anything never fail

CloudWatch Logs:

...."collects all google groups..."
{ "group": "AWS Roles - Redacted", "id": "Redacted", "level": "debug", "msg": "get user", "time": "2023-11-02T18:33:57Z" } 
{ "level": "info", "msg": "get existing aws groups", "time": "2023-11-02T18:33:57Z" }
{ "level": "error", "msg": "error getting aws groups", "time": "2023-11-02T18:33:57Z" } 
status of http response was 401: errorString null

**Comment by danielnovello-pf** [comment]
@ChrisPates Thank you. That was it. Apologies for wasting your time. Much appreciated

**Comment by ChrisPates** [comment]
No worries, I’m working on the cloudformation template at the month, I’ll add a reminder on the field to check when it’s due to expire.

Chris


On 2 Nov 2023, at 20:07, danielnovello-pf ***@***.***> wrote:

﻿


@ChrisPates Thank you. That was it. Apologies for wasting your time. Much appreciated
