### ISSUE TITLE
Serverless Application Repository not updated to 2.x.x

### ISSUE THREAD

**Issue by pecigonzalo** [awslabs/ssosync#169]
**Describe the bug**
The SSOSync SAR has not been updated to any newer version than 1.x.rc. Is SAR no longer supported?

**Expected behavior**
The [SAR](https://eu-west-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync) shows up to date versions of SSOSync

**Comment by ChrisPates** [comment]
The official SAR repo is up to date (see link in the readme). However, non-official SAR apps do exist. 

Which sat arm are you looking at?

Kind regards,

Chris 

On 7 Feb 2024, at 13:35, Gonzalo Peci ***@***.***> wrote:

﻿


Describe the bug
The SSOSync SAR has not been updated to any newer version than 1.x.rc. Is SAR no longer supported?

Expected behavior
The SAR <https://eu-west-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync> shows up to date versions of SSOSync

**Comment by pecigonzalo** [comment]
In using the one linked in the issue, the official one linked from the
reader. The description says its version 1.x.

Maybe the description is outdated?

**Comment by ChrisPates** [comment]
So the header reads:

### SSOSync — version 2.1.2

granted it looks like the **Source code URL** is stuck pointing to an older version.

I'll take a look at getting that updated in the next release. Was there anywhere else you saw erroneous references?

**Comment by pecigonzalo** [comment]
I thought from the source ref that this was referring to 1.x. If that is not the case, then seems like a minor details. It did confuse me :D but for sorry for the noise.
