### ISSUE TITLE
Performance issue with large number of users and groups

### ISSUE THREAD

**Issue by fredericbarthelet** [awslabs/ssosync#17]
**Bug description**

Consider a G Suite organization with 200 users and 200 groups.
In order to sync (add or remove users from this group) AWS SSO group members with G Suite group members, one separate HTTP call to SCIM endpoint is made for every user, for each group, to check wether this user is already in the group or not. This allows building of current AWS SSO users-groups mapping and ensure proper addUserToGroup or removeUserFromGroup operation to match the desired target mapping retrieved from G Suite.

https://github.com/awslabs/ssosync/blob/5c7c352868093cbc141dafc312f4bbd2af29b4ed/internal/sync.go#L154

https://github.com/awslabs/ssosync/blob/5c7c352868093cbc141dafc312f4bbd2af29b4ed/internal/sync.go#L201-L203

With our 200 users and 200 groups, this results in 40.000 HTTP requests made to SCIM, just to get current group-member mapping.

This causes my SAM application to continuously timeout after 5min of HTTP calls.

IMHO, there are 2 options here to improve the situation :
- add a disable-group-sync option to the command to disable group syncing all together for organizations not using group provisioning from G Suite or for large use cases like mine
- check if there is an efficient way to build existing users in AWS SSO groups other than specifically requesting wether one specific user is in one specific group. I'm not familiar with SCIM protocol so I don't know if this is an actual limitation of the protocol or not

WDYT ?

**Comment by Hiryus** [comment]
Hello,

We have the same problem (likely in a lower scale since we only have about 100 users).

Another option to consider would be to add a parameter to list which groups to synchronize.
For example: `ssosync [...] --synced-groups=group_1,group_2,...`
In our case, we only need a handful of groups on AWS so this would tremendously speed up the process.

**Comment by crablab** [comment]
We're looking at syncing close to 5,000 users :sweat_smile:  

Again, we only need to sync one or two groups.

**Comment by mascah** [comment]
Same thing here. A few hundred users and about a hundred groups and the sync process takes over an hour and a half to run. We're going to have to move this out of lambda in the meantime. 

I'm not familiar with SCIM at all, but it would be nice if there was a way to retrieve a list of users in each group and then diff that against gsuite, rather than checking every user for every group, which should cut down the number of HTTP calls to the number of groups that exist.

**Comment by crablab** [comment]
>  A few hundred users and about a hundred groups and the sync process takes over an hour and a half to run.

I've given up doing that and modified the code so we're including specific groups to sync, rather than excluding. 

I personally would like to see this done with webhooks, but again, not sure how SCIM actually works.

**Comment by da3mon-01** [comment]
I did some digging on the Google and AWS side SCIM apis, if this can be improved somehow. GSuite publishes the list of members on /Groups/$groupname, so its easy to get them, AWS did not however, only on the /Users/$username api call, so that is why we have to manually check every user.

If AWS fixes this, we can compare members with 1 API call for each group, and only modify the users that actually need it.

**Comment by mmb-davidsmith** [comment]
@da3mon-01, I was looking at the API and wondering if the issue with efficiency could be replaced with the AWS patch operation. Instead of looking to compare the two groups, just read the group from google, read the users from AWS with ListUsers, and then build the appropriate patch call to replace all users in a group in AWS.

**Comment by ChrisPates** [comment]
This should have been resolved by release v2.x let me know if you are still seeing this issue.
