### ISSUE TITLE
Breaking change on v1.0.0-rc.9 (from v1.0.0-rc.8)

### ISSUE THREAD

**Issue by bfreis** [awslabs/ssosync#40]
**Describe the bug**

When running ssosync v1.0.0-rc.8, the process works fine. When running v1.0.0-rc.9 with the exact same set of parameters, it exits with an error.

**To Reproduce**
1. Download v1.0.0-rc.8
2. Run with:

```
./ssosync \
  --debug \
  --access-token "REDACTED" \
  --endpoint "REDACTED" \
  --google-admin "REDACTED" \
  --google-credentials "credentials.json"
```

3. See the correct output running the sync.

4. Download v1.0.0-rc.9
5. Run with the exact same commands as before
6. See the error:

```
INFO[0000] Syncing AWS users and groups from Google Workspace SAML Application 
INFO[0000] syncing                                       sync_method=groups
DEBU[0000] get google groups                             query=
FATA[0000] googleapi: Error 400: Invalid Input: query, invalid
```

**Expected behavior**
Expected v1.0.0-rc.9 to not have any breaking changes from v1.0.0-rc.8, as none are documented, and this is not a major version bump.

To be very clear: a bump such as rc.8 -> rc.9 should have _absolutely identical_ behavior for a valid set of parameters. Anything different than that makes it a breaking change, which doesn't belong to something like rc.8 -> rc.9.

**Additional context**
Running on Mac OS 11.2.3.

**Comment by grugnog** [comment]
It seems this is related to the change in #36 which appears to have broken the ability to include all groups or all users in the sync (before including/ignoring based on the other parameters).
I think this is because the directory search requires a non-zero-length prefix on the name or email even when using a wildcard - you can't just search on `email:*`, for example - this results in `googleapi: Error 400: Invalid Input, invalid`.

**Comment by cep21** [comment]
I'm still on the previous release and never upgraded due to this issue

**Comment by christiangda** [comment]
@grugnog and @cep21 there are two `sync methods`

```
-s, --sync-method string          Select the sync method to use (users_groups|groups) (default "groups")
```

by default the behaviour is 'groups', which mean that you only want to sync groups and their members, additionally, you can use the filter for groups.

when you use `--sync-method "groups" ` the parameter `--include-groups` doesn't work, so, if you want to sync all users and only groups into `--group-match "g1,g2,g..."` you need to set 

```
--sync-method "users_groups" 
```

**Comment by bfreis** [comment]
The main problem, and the reason I opened this issue, is that something that used to work, doesn't work anymore. 

Even if there's a way to make it work, it means that everyone's automation that relied on that is now blocked and can't be upgraded without spending time figuring out what the problem is and how to fix it.

It basically behaves like a "major version bump", but it's literally an rc8 to an rc9.

**Comment by christiangda** [comment]
@bfreis you need to take into consideration the API Calls in bot sides, Google and AWS SSO, so every time you do a test with many users and groups you are consuming quotas and it could be your weird behaviour, it happened to me too, so it is the reason why I added the second sync method and the groups filter applied in Google API side and not in the code.

Is important to understand the mechanism this lambda is applying, the SCIM part cost to many requests depends on your numbers of users and groups, and unfortunately the AWS SSO API doesn't have a good mechanism to get the existing groups and their members, so the lambda always does more requests than the necessary.

Other important thinks are the "name limitations" has the AWS SSO Groups and Users, that the second major problems I detect under my tests and implementation, so depending on the naming convention you are using in your google groups and users it is sure you are going to have sync problems.

I hope I have time to validate this groups and users names before call the AWS SSO API and avoid unnecessarily request and errors.

**Comment by bfreis** [comment]
There might indeed be good reasons to want such a behavior. It could be an "improvement" for certain scenarios - but it's a _breaking change_ .

It could, and probably should, have been made in such a way that existing automation that doesn't need or want that behavior isn't forced to change or to stay behind.

**Comment by cep21** [comment]
> but it's a breaking change .

Breaking changes are often expected in alpha APIs, but I think the part that goes too far is completely removing the ability to support previous workflow (syncing all groups).

**Comment by bfreis** [comment]
> Breaking changes are often expected in alpha APIs,

Totally agree.

But this isn't tagged Alpha. Not even Beta. It's a Release Candidate. It should be considered stable enough as a potential Release.

Removing features and changing defaults shouldn't even be considered at this point.

It surprises me that someone would propose a PR doing that, and probably even more so that such a PR would be accepted and merged. 

The longer @christiangda and @joshuachong take to fix this, the worst this situation becomes, as now there's a set of features and a default behavior in rc8 that are completely different than in rc9. The longer this mess goes on, the more people will start with rc9 and the more people will then be similarly negatively affect by fixing the mess introduced in rc9.

**Comment by christiangda** [comment]
Guys, 

I created PR #44 , please review and test it to see if your problem was fixed, also I improved the `README.md` file to clarify the use of the flags, leave me a comment or review and improve it in the PR.

**Comment by joshuachong** [comment]
> > Breaking changes are often expected in alpha APIs,
> 
> Totally agree.
> 
> But this isn't tagged Alpha. Not even Beta. It's a Release Candidate. It should be considered stable enough as a potential Release.
> 
> Removing features and changing defaults shouldn't even be considered at this point.
> 
> It surprises me that someone would propose a PR doing that, and probably even more so that such a PR would be accepted and merged.
> 
> The longer @christiangda and @joshuachong take to fix this, the worst this situation becomes, as now there's a set of features and a default behavior in rc8 that are completely different than in rc9. The longer this mess goes on, the more people will start with rc9 and the more people will then be similarly negatively affected by fixing the mess introduced in rc9.

Fully agreed with this. And my apologies on this as well, I could definitely have done better before accepting that merge. 

I've merged @christiangda PR #44 for this.

**Comment by bfreis** [comment]
Hi @joshuachong, @christiangda — #43 and #44 don't fix the issue. Tried with current HEAD.

1) It goes further than v1.0.0-rc.9.

2) It fails with `FATA[0003] status of http response was 404`.

3) The part of the process that it executes it does so still with very different behavior than on v1.0.0-rc.8. Specifically, it used to create groups in AWS SSO named like `my-group-name@my-company.com` (i.e., just like the name in Google), but now it's creating groups called simply `my-group-name`. Changing the default group name is still a breaking change.

4) After having created the group (with the wrong name), it tried to add a user to that group, and failed (i.e., I believe that's what the Fatal error message refers to).

5) At least it didn't touch any other existing groups or users in AWS SSO.

So, the PRs merged still don't fix this breaking change.

**Comment by joshuachong** [comment]
@christiangda - if you don't mind, can you take a look at #44 again?

Otherwise, for the benefit of everyone, may look at reverting to rc.8 and reapply non-breaking changes.

**Comment by christiangda** [comment]
@joshuachong , I don't mind.  Let me check it in details.

**Comment by bfreis** [comment]
@joshuachong — maybe it's time to revert back to rc.8, and delete release rc.9?

It's been quite a long time and this is still an ongoing issue, and the more time passes, the more people will start using rc.9 as their first contact with `ssosync` and those will be negatively impacted when _that_ (broken) behavior ends up being reverted...

I'd suggest also adding proper automated tests for all default behavior to prevent something like this from happening in the future, as it's quite disruptive.

**Comment by christiangda** [comment]
@bfreis 

I fixed the bug related to 404 answers if you want to keep the behaviour of v1.0.0-rc.8 you just need to pass the flag `--sync-method "users_groups"`

I also introduce improvements of the README.md in my last two PR to clarify the use of `--sync-method`

## Local Usage

```bash
git clone https://github.com/awslabs/ssosync.git
cd ssosync/
make go-build
```

```bash
./ssosync --help
```

```bash
A command line tool to enable you to synchronise your Google
Apps (Google Workspace) users to AWS Single Sign-on (AWS SSO)
Complete documentation is available at https://github.com/awslabs/ssosync

Usage:
  ssosync [flags]

Flags:
  -t, --access-token string         AWS SSO SCIM API Access Token
  -d, --debug                       enable verbose / debug logging
  -e, --endpoint string             AWS SSO SCIM API Endpoint
  -u, --google-admin string         Google Workspace admin user email
  -c, --google-credentials string   path to Google Workspace credentials file (default "credentials.json")
  -g, --group-match string          Google Workspace Groups filter query parameter, example: 'name:Admin* email:aws-*', see: https://developers.google.com/admin-sdk/directory/v1/guides/search-groups
  -h, --help                        help for ssosync
      --ignore-groups strings       ignores these Google Workspace groups
      --ignore-users strings        ignores these Google Workspace users
      --include-groups strings      include only these Google Workspace groups, NOTE: only works when --sync-method 'users_groups'
      --log-format string           log format (default "text")
      --log-level string            log level (default "info")
  -s, --sync-method string          Sync method to use (users_groups|groups) (default "groups")
  -m, --user-match string           Google Workspace Users filter query parameter, example: 'name:John* email:admin*', see: https://developers.google.com/admin-sdk/directory/v1/guides/search-users
  -v, --version                     version for ssosync
```

The function has `two behaviour` and these are controlled by the `--sync-method` flag, this behavior could be

1. `groups`: __(default)__
   * The sync procedure work base on Groups, gets the Google Workspace groups and their members, then creates in AWS SSO the users (members of the Google Workspace groups), then the groups and at the end assign the users to their respective groups.
   * This method use: `Google Workspace groups name` --> `AWS SSO groups name`
2. `users_groups`: __(original behavior, previous versions)__
   * The sync procedure is simple, gets the Google Workspace users and creates these in AWS SSO Users; then gets Google Workspace groups and creates these in AWS SSO Groups and assigns users to belong to the AWS SSO Groups.
   * This method use: `Google Workspace groups email` --> `AWS SSO groups name`

Flags Notes:

* `--include-groups` only works when `--sync-method` is `users_groups`
* `--ignore-users` works for both `--sync-method` values.  Example: `--ignore-users user1@example.com,user2@example.com` or `SSOSYNC_IGNORE_USERS=user1@example.com,user2@example.com`
* `--ignore-groups` works for both `--sync-method` values. Example: --ignore-groups group1@example.com,group1@example.com` or `SSOSYNC_IGNORE_GROUPS=group1@example.com,group1@example.com`
* `--group-match` works for both `--sync-method` values and also in combination with `--ignore-groups` and `--ignore-users`.  This is the filter query passed to the [Google Workspace Directory API when search Groups](https://developers.google.com/admin-sdk/directory/v1/guides/search-groups), if the flag is not used, groups are not filtered.
* `--user-match` works for both `--sync-method` values and also in combination with `--ignore-groups` and `--ignore-users`.  This is the filter query passed to the [Google Workspace Directory API when search Users](https://developers.google.com/admin-sdk/directory/v1/guides/search-users), if the flag is not used, users are not filtered.

NOTES:

1. Depending on the number of users and groups you have, maybe you can get `AWS SSO SCIM API rate limits errors`, and more frequently happens if you execute the sync many times in a short time.
2. Depending on the number of users and groups you have, `--debug` flag generate too much logs lines in your AWS Lambda function.  So test it in locally with the `--debug` flag enabled and disable it when you use a AWS Lambda function.
3. `--sync-method "Groups"` and `--sync-method "users_groups"` are incompatible, because the first use the Google group name as an AWS group name and the second one use the Google group email, take this into consideration.

**Comment by bfreis** [comment]
> I fixed the bug related to 404 answers if you want to keep the behaviour of v1.0.0-rc.8 you just need to pass the flag `--sync-method "users_groups"`

No, this is exactly the problem: no one should be expected to have to make any changes to their automation in an rc.8 -> rc.9 upgrade, if they want to _keep the exact same behavior_.

The problem that has to be fixed, and that this bug is all about, is that _using rc.8 with a set of minimal parameters should have **identical** results in rc.9, rc.10, etc_. It shouldn't exit with an error. It shouldn't require parameter changes. It shouldn't result in a different output, or, worse, delete output from rc.8 (like #47 is doing right now).

**Comment by christiangda** [comment]
@bfreis it is not a problem either, what we can do is set the default behaviour to `--sync-method "users_groups"` instead of `--sync-method "groups"`

**Comment by bfreis** [comment]
@christiangda — you're missing the point, and I'm not sure how much clearer I can make it.

You changed the default behavior. You broke everyone else's automations.

**Comment by christiangda** [comment]
@bfreis, yes this is true, but if we back to the previous version it is going to happen in worse, because doesn't exist the option "groups"

**Comment by bfreis** [comment]
The only reason it seems "worse" is because this is taking incredibly long to fix, increasing the amount of people who will be negatively impacted by the fix.

That's why I'm proposing to @joshuachong that we rollback to rc.8 and delete rc.9.

**Comment by cep21** [comment]
Hi,

Any status updates on #48?

Thanks!

**Comment by cep21** [comment]
Hi, is this still relevant?

**Comment by bfreis** [comment]
Nothing has been done to address the breaking change introduced in v1.0.0-rc9, so yes.

**Comment by amit-solanki** [comment]
6 months have passed still neither got an update rx10 nor a fix for rc9 breaking changes

**Comment by bfreis** [comment]
Yup, very frustrating. Seems like the project got abandoned after it got broken. I simply forked, reverted back to rc8, and it's been good enough!

**Comment by bfreis** [comment]
> The longer @christiangda and @joshuachong take to fix this, the worst this situation becomes, as now there's a set of features and a default behavior in rc8 that are completely different than in rc9. The longer this mess goes on, the more people will start with rc9 and the more people will then be similarly negatively affected by fixing the mess introduced in rc9.

As predicted over 6 months ago... we got exactly there: https://github.com/awslabs/ssosync/issues/46#issuecomment-978370811
