### ISSUE TITLE
ssosync and control tower preconfigured groups

### ISSUE THREAD

**Issue by nickvanwegen** [awslabs/ssosync#50]
Hi, This is more of a question i think than a request. (Just could not find this anywhere)

**Is your feature request related to a problem? Please describe.**

I am using ssosync in combination with control tower.
Now control tower comes with some aws sso preconfigured  groups. 
If i run ssosync it was always delete the preconfigured groups from aws sso which are linked to the control tower setup. 

it seems like ssosync only takes in account the groups it can find in its filter per unique run.

**Describe the solution you'd like**

I would like to sync users/groups with or without a filter from G suite to aws sso without deleting the preconfigured groups that control tower creates. 

**Describe alternatives you've considered**

none i would just like to know if this is possible to do with ssosync.

**Comment by varunchandak** [comment]
I don't think you can have more than 1 identity provider in AWS SSO, it's either Control Tower or External provider

**Comment by ChrisPates** [comment]
Control Tower does come with preconfigured groups, and with official SAML+SCIM integrations (AzureAD, Okta) then the groups can be provisioned back into the upstream IDP (where supported). SSOSync only has readonly access, to the Google Workspace Directory (by design), so can't replicate them to the IDP. Since it treats the Google Workspace Directory as the authoritative source and the groups don't exist there it removes them. 

If you wish to retain them, then you could create equivalent groups in Google Workspaces before enabling SSOSync. Also @varunchandak is correct, AWS SSO only supports a single upstream IDP, so if complicated federated groups of users need to be supported then, a different IDP is required.
